name: Run tests on any Push event
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - uses: actions/setup-python@v1
       with:
         python-version: '3.10'
         architecture: 'x64'    
     - name: Install requirements
       run: |
        python -m pip install --upgrade pip
        pip install -r project2/requirements.txt
     - name: Check pylint correction 
       run: |
          for file in $(find project2/modules/ -name '*.py')
          do
            pylint --disable=C0114,C0115,E0604 "$file" --fail-under=6.0;
          done
     - name: Run tests
       run: python -m pytest --import-mode=append project2/check_tst/tests.py
 

